name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IS_PROD: "false"

jobs:
  backend-ci:
    uses: DCC-BS/ci-workflows/.github/workflows/python-backend-ci.yml@v9
    with:
      python_versions: '["3.13"]'
      quality_python_version: "3.13"
      check_command: "make check"
      test_command: "make test"
